create table if not exists sys_tenant (
    id bigint generated by default as identity primary key,
    tenant_code varchar(64) not null,
    tenant_name varchar(128) not null,
    is_default smallint not null default 0
);

create table if not exists sys_group (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    group_code varchar(64) not null,
    group_name varchar(128) not null,
    parent_id bigint,
    ancestors varchar(512),
    is_default smallint not null default 0
);

create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null,
    display_name varchar(128),
    email varchar(128),
    mobile varchar(32),
    status smallint not null default 1,
    group_id bigint,
    tenant_id bigint,
    register_source varchar(32),
    password_version integer not null default 1,
    failed_login_attempts integer not null default 0,
    locked_until timestamp,
    deleted smallint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists sys_auth (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    identity_type varchar(32) not null,
    principal_key varchar(191) not null,
    credential_hash varchar(255),
    metadata_json varchar(2048),
    enabled smallint not null default 1,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists sys_role (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    role_code varchar(64) not null,
    role_name varchar(128) not null,
    data_scope varchar(32) not null default 'SELF',
    enabled smallint not null default 1
);

create table if not exists sys_permission (
    id bigint generated by default as identity primary key,
    tenant_id bigint,
    permission_code varchar(128) not null,
    permission_name varchar(128) not null,
    permission_type varchar(32) not null,
    enabled smallint not null default 1
);

create table if not exists sys_user_role (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null
);

create table if not exists sys_group_role (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    role_id bigint not null
);

create table if not exists sys_role_permission (
    id bigint generated by default as identity primary key,
    role_id bigint not null,
    permission_id bigint not null
);

create table if not exists sys_login_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    principal varchar(191),
    login_type varchar(32) not null,
    result varchar(32) not null,
    ip varchar(64),
    user_agent varchar(512),
    location varchar(255),
    reason varchar(255),
    created_at timestamp not null default current_timestamp
);

create table if not exists sys_security_event (
    id bigint generated by default as identity primary key,
    event_type varchar(64) not null,
    user_id bigint,
    tenant_id bigint,
    detail_json varchar(4096),
    ip varchar(64),
    created_at timestamp not null default current_timestamp
);

create table if not exists sys_token_blacklist (
    id bigint generated by default as identity primary key,
    jti varchar(128) not null,
    user_id bigint not null,
    expire_at timestamp not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists sys_user_session_policy (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    policy_code varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists sys_user_session (
    id bigint generated by default as identity primary key,
    session_id varchar(64) not null,
    user_id bigint not null,
    username varchar(64) not null,
    tenant_id bigint,
    client_id varchar(128),
    device_type varchar(32),
    device_name varchar(128),
    user_agent varchar(512),
    ip varchar(64),
    status varchar(32) not null default 'ACTIVE',
    last_seen_at timestamp,
    access_expire_at timestamp,
    refresh_expire_at timestamp,
    revoked_at timestamp,
    revoke_reason varchar(64),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists sys_qr_scene (
    id bigint generated by default as identity primary key,
    scene_code varchar(64) not null,
    status varchar(32) not null,
    scanned_user_id bigint,
    scanned_at timestamp,
    approved_user_id bigint,
    approved_at timestamp,
    consumed_at timestamp,
    expire_at timestamp not null,
    created_at timestamp not null default current_timestamp
);
